version: "3.5"
services:
  test:
    build:
      context: .
      target: development

    # NOTE: use 'image' for development
    image: test:development

    # NOTE: add 'command' for development
    entrypoint:
      - dumb-init
      - --
    command: npm run dev

    # NOTE: add environment file for development
    # env_file: ./conf/.env

    ports:
      - "9515:9515"

    # NOTE: the container path must match APP_PATH above
    # NOTE: node_modules must be added here so container uses modules from its own volume
    volumes:
      - .:/opt/test:rw
      - /opt/test/node_modules

    networks:
      - test-network

# networking specifics
networks:
  test-network:
    driver: bridge
